services:
  - type: web
    name: recipe-book-api
    env: python
    buildCommand: "pip install -r requirements.txt && python seed_data.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7